[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version" # prevent Netlify npm install

[build]
  publish = "dist"
  command = "npm run generate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
